### ISSUE TITLE
Map not showing on release build

### ISSUE THREAD

**Issue by woshikie** [geospoc/v-mapbox#167]
As per title.
Tested on the following App.vue:
```javascript
<template>
  <div id="app">
    <MglMap class="mglmap" container="map" :zoom="10.5" :access-token="accessToken" :map-style="mapStyle" :center="sgCenter">
      <MglGeolocateControl/>
      <MglNavigationControl/>
    </MglMap>
  </div>
</template>

<script>
import 'mapbox-gl/dist/mapbox-gl.css';
import 'v-mapbox/dist/v-mapbox.css';
import '@mapbox/mapbox-gl-geocoder/dist/mapbox-gl-geocoder.css';
import {MglMap, MglNavigationControl, MglGeolocateControl} from 'v-mapbox'
export default {
  name: 'App',
  components: {MglMap, MglNavigationControl, MglGeolocateControl},
  data(){
    return {
      accessToken: '<omitted>',
      mapStyle: 'mapbox://styles/mapbox/dark-v9',
      sgCenter: [103.82161, 1.35433],
    };
  }
}
</script>
<style scoped>
.mglmap {
  height: 100vh;
  position: absolute;
  z-index: 0;
}
</style>
```

map works on `npm run serve`, `npm run build --mode development` but ***not*** on `npm run build`

***Edit:*** Changed test code

**Comment by vinayakkulkarni** [comment]
```diff
- import {MglMap, MglNavigationControl, MglGeolocateControl} from 'vue-mapbox'
+ import { MglMap, MglNavigationControl, MglGeolocateControl } from 'v-mapbox'
```

seems you're importing the wrong package

**Comment by woshikie** [comment]
Updated test code with suggestion. Still unable to see the map on release build

**Comment by vvavepacket** [comment]
@vinayakkulkarni  I'm also facing the same issue. New release build. And map is not loading...

**Comment by vvavepacket** [comment]
@vinayakkulkarni 
I'm seeing 100% width and height being occupied, but still map is blank.  Do you have some samples where you tested this with latest build? I appreciate your help

![image](https://user-images.githubusercontent.com/8295642/97520066-c1991a00-1970-11eb-92ba-698e3a38d91d.png)

**Comment by vinayakkulkarni** [comment]
@vvavepacket: can you reproduce this with a demo repo or codesandbox?

**Comment by woshikie** [comment]
@vinayakkulkarni here you go https://github.com/woshikie/mapbox-bug-demo

**Comment by vinayakkulkarni** [comment]
@woshikie & @vvavepacket: I've fixed some minor issues, released a new version & have done a demo on codesandbox.

[![Edit v-mapbox-map-demo](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/v-mapbox-map-demo-k1l1n?fontsize=14&hidenavigation=0&theme=dark)

**Comment by woshikie** [comment]
I have updated [my repo](https://github.com/woshikie/mapbox-bug-demo) with the latest package and this is the output from my `npm run build`.

[dist.zip](https://github.com/geospoc/v-mapbox/files/5461659/dist.zip)

You can see for yourself that the map is not showing. It is showing, however, on debug builds, which we can see on CodeSandbox or `npn run serve`

If you don't have a development web server to run the files, you can use python as a web server.
Assuming you are using python 3 and you extracted the zip file to your current working directory:
`python -m http.server --directory dist`
You should be able to reach your python web server on http://localhost:8000 (by default)

**Comment by vvavepacket** [comment]
@woshikie  @vinayakkulkarni 

Thanks for the update, unfortunately the issue still stands...

I can confirm that release build is not working. I deployed it to my local web server and it doesn't work. I inspected the layout and it seems that the css files are not being loaded properly, as I can see the classes are not attached to the mapbox divs.
